module.exports=[
  {
    categoryId:1001,
    categoryName:'优选水果',
    introImg:'../../server/resources/fruits/fruits1.jpg',
    goods:[
      {
        sku:'123444a',
        name:'文西砂糖桔',
        goodsPic:'../../server/resources/fruits/fruits2.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'400-450g/盒',
        hotPrice:'¥12.8',
        price:'¥15.8'
      },
      {
        sku:'23578a',
        name:'四川双流奶油草莓',
        goodsPic:'../../server/resources/fruits/fruits3.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'250-300g/盒',
        hotPrice:'¥28.8',
        price:'¥30.8'
      },
      {
        sku:'76655a',
        name:'皇帝柑',
        goodsPic:'../../server/resources/fruits/fruits4.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'300-400g/盒',
        hotPrice:'¥11.8',
        price:'¥14.9'
      },
    ]
  },
  {
    categoryId:1002,
    categoryName:'牛奶面包',
    introImg:'../../server/resources/milkbread/milkbread1.jpg',
    goods:[
      {
        sku:'123444a',
        name:'纯享益生菌风味发酵乳原味',
        goodsPic:'../../server/resources/milkbread/milkbread2.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'330g',
        hotPrice:'¥7.9',
        price:'¥8.5'
      },
      {
        sku:'23578a',
        name:'涨芝士啦风味发酵乳',
        goodsPic:'../../server/resources/milkbread/milkbread3.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'180ml',
        hotPrice:'¥3.8',
        price:'¥6.8'
      },
      {
        sku:'76655a',
        name:'三元轻能黄桃+大麦优酪乳',
        goodsPic:'../../server/resources/milkbread/milkbread4.jpg',
        get1free:1,
        carefullyChosen:1,
        unit:'250g',
        hotPrice:'¥8.9',
        price:'¥9.9'
      },
    ]
  },
  {
    categoryId:1003,
    categoryName:'卤味熟食',
    introImg:'../../server/resources/cookedfood/cookedfood1.jpg',
    goods:[
      {
        sku:'123444a',
        name:'飘香鸭锁骨(微辣)',
        goodsPic:'../../server/resources/cookedfood/cookedfood2.jpg',
        get1free:0,
        carefullyChosen:1,
        unit:'150g',
        hotPrice:'¥9.9',
        price:'¥14'
      },
      {
        sku:'23578a',
        name:'飘香卤鱼豆腐(微辣)',
        goodsPic:'../../server/resources/cookedfood/cookedfood3.jpg',
        get1free:0,
        carefullyChosen:1,
        unit:'138g/盒',
        hotPrice:'¥10',
        price:'¥18'
      },
      {
        sku:'76655a',
        name:'飘香鸭脖微辣',
        goodsPic:'../../server/resources/cookedfood/cookedfood4.jpg',
        get1free:0,
        carefullyChosen:1,
        unit:'168g',
        hotPrice:'¥15',
        price:'¥18'
      },
    ]
  },
  {
    categoryId:1004,
    categoryName:'饮料酒水',
    introImg:'../../server/resources/Drinks/Drinks1.jpg',
    goods:[
      {
        sku:'123444a',
        name:'加多宝金罐凉茶',
        goodsPic:'../../server/resources/Drinks/Drinks2.jpg',
        get1free:0,
        carefullyChosen:0,
        unit:'310ml',
        hotPrice:'¥5',
        price:''
      },
      {
        sku:'23578a',
        name:'农夫水溶C100柠檬',
        goodsPic:'../../server/resources/Drinks/Drinks3.jpg',
        get1free:0,
        carefullyChosen:0,
        unit:'445ml',
        hotPrice:'¥5',
        price:''
      },
      {
        sku:'76655a',
        name:'美汁源,果粒橙,橙汁饮料',
        goodsPic:'../../server/resources/Drinks/Drinks4.jpg',
        get1free:0,
        carefullyChosen:0,
        unit:'445ml',
        hotPrice:'¥4',
        price:''
      },
    ]
  },

];
